CREATE DATABASE contacts;

CREATE TABLE `contacts`.`contacts` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(60) NOT NULL,
    `last_name` VARCHAR(60) NOT NULL,
    `phone` VARCHAR(13) UNIQUE NOT NULL,
    `country` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
);

insert into contacts (first_name, last_name, phone, country) values ('Lurlene', 'Merrydew', '291-668-3440', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Ignatius', 'Jedrzejewsky', '974-912-1246', 'JP');
insert into contacts (first_name, last_name, phone, country) values ('Muffin', 'Ricardon', '783-289-8239', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Harry', 'Dike', '529-129-0574', 'AE');
insert into contacts (first_name, last_name, phone, country) values ('Hermia', 'Delbergue', '425-224-2947', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Jacob', 'Sargerson', '446-185-2191', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Randie', 'Reedshaw', '544-483-0218', 'CI');
insert into contacts (first_name, last_name, phone, country) values ('Ludovika', 'Stranaghan', '119-518-1561', 'AL');
insert into contacts (first_name, last_name, phone, country) values ('Madalyn', 'Adolfsen', '781-367-9718', 'TH');
insert into contacts (first_name, last_name, phone, country) values ('Lyn', 'Benazet', '434-993-7636', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Tamra', 'Echallie', '959-839-8007', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Yalonda', 'Pirrone', '904-944-5361', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Melicent', 'Soreau', '201-946-2423', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Roselin', 'Vanetti', '591-908-6313', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Ramona', 'Chessum', '663-110-4813', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Shara', 'Menco', '990-183-4895', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Nari', 'Horsburgh', '242-205-5825', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Tootsie', 'Shorland', '562-956-2994', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Ole', 'Salliss', '504-673-4674', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Daisie', 'Horsey', '738-844-6384', 'MK');
insert into contacts (first_name, last_name, phone, country) values ('Yevette', 'Louche', '917-502-6851', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Robin', 'Scourge', '175-714-6293', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Igor', 'Frowen', '447-231-7158', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Rose', 'Kench', '496-655-7075', 'IE');
insert into contacts (first_name, last_name, phone, country) values ('Bret', 'Ackenson', '246-624-3538', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Elaina', 'McLenaghan', '323-774-3530', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Cullan', 'Lafflina', '837-145-3470', 'ID');
insert into contacts (first_name, last_name, phone, country) values ('Savina', 'Mottley', '219-131-6028', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Tabbie', 'Winkell', '660-403-3857', 'RU');
insert into contacts (first_name, last_name, phone, country) values ('Dominik', 'Nockells', '245-992-0678', 'IR');
insert into contacts (first_name, last_name, phone, country) values ('Truman', 'Sigsworth', '560-101-9271', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Kassi', 'Pavlenkov', '349-787-6902', 'FI');
insert into contacts (first_name, last_name, phone, country) values ('Osmund', 'Withnall', '493-869-4851', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Carly', 'Meriguet', '194-911-6561', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Eulalie', 'Mephan', '686-822-5071', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Merrel', 'Barnet', '821-497-4050', 'RE');
insert into contacts (first_name, last_name, phone, country) values ('Coretta', 'Vallance', '444-720-7811', 'ZA');
insert into contacts (first_name, last_name, phone, country) values ('Noah', 'Bridgeland', '360-168-3771', 'SE');
insert into contacts (first_name, last_name, phone, country) values ('Lisha', 'Jon', '502-226-3914', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Richart', 'Cornu', '274-462-1428', 'JO');
insert into contacts (first_name, last_name, phone, country) values ('Julianna', 'Ekless', '795-337-9519', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Goddart', 'Duffrie', '805-118-2712', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Lynnett', 'Devonport', '991-390-0255', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Melvyn', 'Karsh', '910-906-3898', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Tyrone', 'Tarbett', '491-530-5641', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Libbey', 'Pinks', '216-764-9908', 'ID');
insert into contacts (first_name, last_name, phone, country) values ('Dottie', 'Rodder', '654-842-6053', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Loren', 'Gaukrodge', '804-444-4869', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Porter', 'Leonida', '689-549-4415', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Clementia', 'Boulder', '826-265-5684', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Honoria', 'Sterricker', '665-665-3491', 'UA');
insert into contacts (first_name, last_name, phone, country) values ('Issi', 'Della', '565-172-0405', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Irv', 'Saffrin', '130-173-5335', 'ID');
insert into contacts (first_name, last_name, phone, country) values ('Geralda', 'Tilsley', '996-709-2126', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Viviana', 'Chrispin', '188-416-5997', 'RU');
insert into contacts (first_name, last_name, phone, country) values ('Skell', 'Gainforth', '448-768-0476', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Susie', 'Crosse', '696-557-8728', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Angy', 'Coate', '265-809-7739', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Levi', 'Newland', '221-155-7451', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Faye', 'Priddey', '973-192-7718', 'VN');
insert into contacts (first_name, last_name, phone, country) values ('Randy', 'Garlicke', '444-488-7632', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Latashia', 'Exeter', '211-325-0456', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Laurice', 'Pirot', '609-494-4222', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Deidre', 'Paulsson', '487-702-8558', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Dalli', 'Longfield', '397-661-2363', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Car', 'Thrustle', '626-689-6169', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Rodrick', 'Leftbridge', '482-982-9615', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Derry', 'Petrillo', '721-714-1117', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Franz', 'Glover', '695-654-5871', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Giulia', 'Dradey', '724-998-1113', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Berk', 'Ewer', '772-316-4411', 'AZ');
insert into contacts (first_name, last_name, phone, country) values ('Chloe', 'St. Ledger', '102-522-2833', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Archibold', 'Gittose', '642-489-6836', 'PT');
insert into contacts (first_name, last_name, phone, country) values ('Alwin', 'Nail', '304-233-0046', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Giustino', 'Corain', '197-516-6921', 'TN');
insert into contacts (first_name, last_name, phone, country) values ('Robers', 'Jeffry', '883-369-3761', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Justinian', 'Stratley', '607-967-1645', 'KZ');
insert into contacts (first_name, last_name, phone, country) values ('Row', 'Lehrmann', '199-874-3542', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Lari', 'Minchenton', '493-325-2358', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Riane', 'Janek', '266-483-8890', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Deane', 'Sullens', '378-435-6570', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Nikolos', 'Baynes', '815-548-6054', 'RU');
insert into contacts (first_name, last_name, phone, country) values ('Corilla', 'Phython', '207-181-2785', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Tedmund', 'Donavan', '976-711-3083', 'RU');
insert into contacts (first_name, last_name, phone, country) values ('Dorian', 'McIlvenny', '446-843-4556', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Adiana', 'Limpkin', '504-279-7985', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Lynn', 'Josef', '307-545-5855', 'ET');
insert into contacts (first_name, last_name, phone, country) values ('Nicolai', 'Iglesia', '927-462-5402', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Evyn', 'Kording', '497-556-4830', 'CN');
insert into contacts (first_name, last_name, phone, country) values ('Indira', 'Bullivent', '312-801-0728', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Bev', 'Blabber', '786-400-4255', 'PE');
insert into contacts (first_name, last_name, phone, country) values ('Melisa', 'Barabisch', '315-168-9407', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Guglielmo', 'Baelde', '423-757-3022', 'GR');
insert into contacts (first_name, last_name, phone, country) values ('Noelani', 'Sturdgess', '592-184-7076', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Sofia', 'Wrankling', '313-439-0327', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Bekki', 'Mosco', '764-531-8837', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Bard', 'Gallymore', '115-313-5144', 'PH');
insert into contacts (first_name, last_name, phone, country) values ('Stefano', 'Demaid', '979-922-1933', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Gus', 'Overland', '262-593-3988', 'US');
insert into contacts (first_name, last_name, phone, country) values ('Francisco', 'Dundon', '905-642-4043', 'US');
